Update denseTraj.py
need to specify that t1 and t2 are ints. Otherwise, it will output an error when trying to access the elements in featSpat. 

Error message: 
tube1 = traj2tube(featSpat[t1,0], featSpat[t1,1:], xmax, ymax, regionSize)
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices